apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops
  labels:
    app: devsecops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsecops
  template:
    metadata:
      labels:
        app: devsecops
    spec:
      containers:
        - name: devsecops
          image: 767397705569.dkr.ecr.us-west-2.amazonaws.com/devsecops:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
