name: Snyk IaC Scan

on: push

jobs:
  snyk:
    name: Snyk IaC Scan
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Snyk (Install the Snyk CLI)
      - name: Set up Snyk
        uses: snyk/actions/setup@master
        with:
          version: 'latest'

      # Step 3: Run the Snyk IaC scan
      - name: Snyk IaC Scan
        run: snyk iac test /home/runner/work/java-reachability-playground/infrastructure/main.tf --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
