name: build
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          args: --report

      - name: Set up Snyk
        uses: snyk/actions/setup@v2
        with:
          version: 'latest'

      # Step 3: Run the Snyk IaC scan
      - name: Snyk IaC Scan
        run: snyk iac test --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    
