name: Example workflow for Maven using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error : true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  OWASP_ZAP_SCAN:
    runs-on: ubuntu-latest
    name: Scan the web application with ZAP
    steps:
      - name: Checkout
        uses: actions/Checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'zaproxy/zap-stable'
          target: 'https://www.zaproxy.org'
          rules_file_name": '.zap/rules/tsv'
          cmd_options: '-a'
